FROM node:20.5.0

WORKDIR /app/medusa

RUN mkdir dist

COPY package*.json ./

COPY develop.sh .

COPY .env .

COPY medusa-config.js .

RUN apt-get update

RUN npm ci

RUN apt-get update || : && apt-get install python3 python-is-python3 -y

RUN npm install -g npm@latest

RUN npm install -g @medusajs/medusa-cli@latest

RUN npm install --loglevel=error

COPY --from=builder /app/medusa/dist ./dist

EXPOSE 9000

ENTRYPOINT ["./develop.sh", "start"]
